pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false,
                 extensions: [], submoduleCfg: [],
                  userRemoteConfigs: [[credentialsId: '<credentials-id>', 
                  url: 'https://github.com/<repo-owner>/<repo-name>.git']]])
            }
        }
        stage('Compile') {
            steps {
                sh './gradlew compileJava'
            }
        }
        stage('Unit Tests') {
            steps {
                sh './gradlew test'
            }
        }
    }
}
