pipeline {
    agent any // Cualquier maquina podrá ejecutarlo
    stages {
        stage('Checkout') { /* Este codigo de checkout lo sacamos mediante un Snippets de Jenkins*/
            steps{
                checkout scmGit(branches: [[name: '*/master']],
                extensions: [], 
                userRemoteConfigs: [[url: 'https://github.com/josekuma/bootcampDevOps.git']])

         
            }

        }
        stage('Compile') { // Este es el stage Compile que sirve para compilar el codigo de java mediante Gradle
            steps {
                /* Tenemos que hacer un cd a la ruta relativa de nuestro repo para encontrar el source de nuestra app, justo donde se encuentran nuestros archivos gradle.
                Lo del chmod es para darle permisos de ejecucion en caso de que no los tenga */
                    sh  '''
                        cd "./03-pipelines/Ejercicio 1/jenkins-resources/calculator/" 
                        chmod +x gradlew
                        ./gradlew compileJava
                    '''
                

            
            }
        }
        stage('Unit Tests') {
            steps { // Esta fase es para hacer testing de nuestra app

                         sh '''
                         cd "./03-pipelines/Ejercicio 1/jenkins-resources/calculator/"
                         chmod +x gradlew
                         ./gradlew test
                         '''
                 
            }
        }
    }
}
