pipeline {
    agent {
        docker {
            image 'gradle:6.6.1-jre14-openj9'
            args '--network jenkins_default --link docker:docker --volume /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '<credentials-id>', url: 'https://github.com/<repo-owner>/<repo-name>.git']]])
            }
        }
        stage('Compile') {
            steps {
                sh 'gradle compileJava'
            }
        }
        stage('Unit Tests') {
            steps {
                sh 'gradle test'
            }
        }
    }
}
º