version: "3.8"
services:
  some-mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - lemoncode-challenge
    volumes:
      - mongo-volume-lemon:/data/db
  topics-api:
    image: backend
    networks:
      - lemoncode-challenge
  frontend:
    image: frontend
    networks:
      - lemoncode-challenge
    ports:
      - 8081:3000
    tty: true
    
networks:
  lemoncode-challenge:
    driver: bridge

volumes:
  mongo-volume-lemon:
