pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps{
checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/josekuma/bootcampDevOps.git']])

         
            }

        }
        stage('Compile') {
            steps {
                    dir('/03-pipelines/Ejercicio 1/jenkins-resources/calculator/'){
                    sh './gradlew compileJava'

                    }

            
            }
        }
        stage('Unit Tests') {
            steps {
                sh './gradlew test'
            }
        }
    }
}
