pipeline {
    agent {
        docker {
            image 'gradle:6.6.1-jre14-openj9'
        }
    }
    stages {
        stage('Checkout') {
            steps {

                checkout scmGit(branches: [[name: '*/master']],
                extensions: [], 
                userRemoteConfigs: [[url: 'https://github.com/josekuma/bootcampDevOps.git']])

            }
        }
        stage('Compile') {
            steps {
                dir("$WORKSPACE/Ejercicio1/jenkins-resources/calculator"){
                 sh  '''
                chmod +x gradlew
                gradle compileJava
                '''
                }
             
            }
        }
        stage('Unit Tests') {
            steps {

                dir("$WORKSPACE/Ejercicio1/jenkins-resources/calculator"){
                sh  '''
                chmod +x gradlew
                gradle test
                '''
                }
            }
        }
    }
}
